AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  plushenomeche-campaign

  Sample SAM Template for plushenomeche-campaign
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Environment:
      Variables:
        KMS_KEY_ID: !GetAtt EncryptionKey.KeyId
Resources:
  EncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Encrypt the signature of the sent emails
      Enabled: True
      EnableKeyRotation: False
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: False
      KeyPolicy:
        Version: 2012-10-17
        Id: default-key-policy
        Statement:
          - Sid: Enable Root User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'

  UnsubscriptionEventsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "Signature"
          AttributeType: "S"
        - 
          AttributeName: "Timestamp"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "Signature"
          KeyType: "HASH"
        - 
          AttributeName: "Timestamp"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "UnsubscribeEvents"

  FilterHook:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: plushenomeche-filter-hook/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Architectures:
        - x86_64
      Policies:
        - KMSEncryptPolicy:
            KeyId: !GetAtt EncryptionKey.KeyId

  EmailsApplication:
    Type: AWS::Pinpoint::App
    Properties: 
      Name: PlushenomecheEmails

  FilterHookResourcePolicy:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !Ref FilterHook
      Principal: pinpoint.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub 'arn:aws:mobiletargeting:${AWS::Region}:${AWS::AccountId}:apps/*'

  EmailsApplicationSettings:
    Type: AWS::Pinpoint::ApplicationSettings
    Properties: 
      ApplicationId: !Ref EmailsApplication
      CampaignHook: 
          LambdaFunctionName: !GetAtt FilterHook.Arn
          Mode: FILTER
      CloudWatchMetricsEnabled: True

  UnsubscribeApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: plushenomeche-unsubscribe-api/
      Handler: app.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        - PinpointEndpointAccessPolicy:
            PinpointApplicationId: !Ref EmailsApplication
        - DynamoDBWritePolicy:
            TableName: !Ref UnsubscriptionEventsTable
        - KMSDecryptPolicy:
            KeyId: !GetAtt EncryptionKey.KeyId
        - Statement:
            Sid: SesPutSuppressedDestinationPolicy
            Effect: Allow
            Action:
              - ses:PutSuppressedDestination
            Resource: '*'
      Events:
        Unsubscribe:
          Type: HttpApi # More info about API Event Source: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#httpapi
          Properties:
            Path: /unsubscribe
            Method: get
Outputs:
  FilterHook:
    Description: 'FilterHook Lambda Function ARN'
    Value: !GetAtt FilterHook.Arn
  FilterHookfIamRole:
    Description: 'Implicit IAM Role created for FilterHook function'
    Value: !GetAtt FilterHookRole.Arn
  UnsubscribeEndpoint:
      Description: "API Gateway endpoint URL for Prod stage for Unsubscribe function"
      Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/unsubscribe/"
  UnsubscribeApi:
    Description: "Unsubscribe Api Lambda Function ARN"
    Value: !GetAtt UnsubscribeApi.Arn
